apiVersion: v1
kind: Secret
metadata:
  name: next-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "QVNJQVVCTE1GWEVBNTRFSk9NTTI="
  AWS_SECRET_ACCESS_KEY: "VVRIMEFUYUljYTk4M0d1WWhIaDJ2MHlkSTRaMmVjNWZhdnlINjNiYw=="
  AWS_SESSION_TOKEN: "SVFvSmIzSnBaMmx1WDJWakVQei8vLy8vLy8vLy93RWFDWFZ6TFdWaGMzUXRNU0pHTUVRQ0lCbVVwR2N1VGRVcC9BaWRUYnFFNGszYU13aXhSZnhPNjErcno1SVpWbWlrQWlCS1QvMjRVbytveGt3eTRWN0k5bXJYRENCMFIvWmdkV1BLaG1iSEtkdDNuU3JUQVFoMUVBQWFEREkzTnpjNE9URXlPRGsyTVNJTW1wUjIxQnJ1ekhMSHQ2VjNLckFCd3NyOTRmYmREdVM5MWpqREZwWFQzWklBYlQ5U2ZKditKWExmVFEwMTV3bkxsSUlhZGp3RGN1ZEl4NmsyRUYxWGozbDM5UEg5Vlc1TmNvN0JQZzh1RlUxNUpqSlNRdzhMNTVydk51QkR2TS9sYnRFWkdVTWo3YlZDa3lEa21iK2ZrUzZ2VFVCaDc3Njgza3ZMRWdWRnR6OU9yZWw3ekVOTW9tRmJPWnJvc3lYQ1l3ZWFMSVJxQlQ0dldaS0VMclFSZ3l4QjdyRzA0S1B4VjFGMUFqVGk0OHBEYlJjLzVGak9yRTBXei9vVlVVQXd3NC9VdndZNm1RRldDM3NpZzBycFdxNXBaSlNTWkU0em5vdE5WMU5SM21LWnNwODZBaUZ1MkNmdTd2czRLRDVZZU9kV3lWcFB4L0Y3YkVmbEhTY29KeVRENEVLc0xibXBRcWtWRlh0SXh1M0VIN2FGN25ydVgrMGhJc2Vna20yUTc0M1AzL3BxYUt1Mi9wRUNSbjd5SHN6TzdzUXNPMXZkdEhEbWpmN29ETWlJVXRoNDJ6a2g2YzNVVzM2WWdSMkYvNHZsZnFyejh0Y1p1R25LT2NGU0NUcz0="
