apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-pod
  name: my-pod
  namespace: production
spec:
  serviceAccountName: s3-service-account-v3
  initContainers:
  - image: amazon/aws-cli
    name: my-aws-cli
    command: ['aws', 's3', 'ls', 's3://bucket-tirtahakimp35/']
  containers:
  - image: nginx
    name: my-pod
    ports:
    - containerPort: 80