apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
data:
  ACCESS_KEY: "AWS_ACCESS_KEY"
  SECRET_KEY: "AWS_SECRET_TOKEN"
  SESSION_TOKEN: "SESSION_TOKEN_WHEN_USE_AWS_ACADEMY"
