apiVersion: v1
kind: ConfigMap
metadata:
  name: go-health-configmap
data:
  MYSQL_HOST: 'mysql-service.default.svc.cluster.local'
  MYSQL_PORT: '3306'
  MYSQL_DATABASE: 'gohealthdb'

  REDIS_HOST: 'redis-service.default.svc.cluster.local'
  REDIS_PORT: '6739'
  PORT: '8080'
  HOST: '0.0.0.0'