apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-health-deployment
spec:
  selector:
    matchLabels:
      app: go-health
  template:
    metadata:
      labels:
        app: go-health
    spec:
      containers:
      - name: go-health
        image: tirtahakimpambudhi/go-health
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef: 
              name: 'go-health-secret'
          - configMapRef:
              name: 'go-health-configmap'

---

apiVersion: v1
kind: Service
metadata:
  name: go-health-service
spec:
  selector:
    app: go-health
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-health-ingress
  labels:
    name: go-health-ingress
spec:
  rules:
  - host: go-health.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-health-service
            port: 
              number: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-health-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-health-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
