apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: bGtzZGl5MjAyNWFkbWluMTIz # lksdiy2025admin123
  MARIADB_USER: bGtzZGl5MjAyNXVzZXI= # lksdiy2025user
  MARIADB_PASSWORD: bGtzZGl5MjAyNXBhc3M= # lksdiy2025pass
