services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=student_db
      - REDIS_ADDR=redis:6379
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=your_access_key
      - AWS_SECRET_KEY=your_secret_key
      - AWS_BUCKET_NAME=your_bucket_name
    restart: always