apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
data:
  ACCESS_KEY: "QUtJQVVCTE1GWEVBM1pMWUxBUEo="
  SECRET_KEY: "V1hyK3BsbHFFck95ODlNUERsR1hsYWcvVk1sN3d2ekcraGRGRVB4eA=="
  # SESSION_TOKEN: "SESSION_TOKEN_WHEN_USE_AWS_ACADEMY"
