apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-service-account-v3
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::277789128961:role/$ROLE_NAME # eks-s3-role-v3
